import React from "react";
import DayList from "./DayList";
import Appointment from "./Appointment";
import { getAppointmentsForDay, getInterview, getInterviewersForDay } from "helpers/selectors";
import { useApplicationData } from "hooks/useApplicationData";

import "components/Application.scss";

// This function/file essentially manages the rendering of all other components on a single page. "Essentially," because the rendering of the many different Appointment components is technically handled elsewhere, but the Appointment component itself and the props it uses start in the Application component

export default function Application(props) {
  const {
    state,
    setDay,
    bookInterview,
    cancelInterview
  } = useApplicationData(); // see "/src/hooks/useApplicationData.js" for more info

  const dailyAppointments = getAppointmentsForDay(state, state.day); // see "/src/helpers/selectors.js" for more info
  const dailyInterviewers = getInterviewersForDay(state, state.day); // see "/src/helpers/selectors.js" for more info

  // Arrays generated by above helpers contain objects with all relevant data needed to be rendered by the app. The following map method uses that information to create an array containing Appointment components provided with the props necessary to determine which mode they will display, and what their contents will be.

  const scheduleItems = dailyAppointments.map(appointment => {
    const interview = getInterview(state, appointment.interview); // see "/src/helpers/selectors.js" for more info
    return (
      <Appointment
        key={appointment.id}
        {...appointment}
        interview={interview}
        interviewers={dailyInterviewers}
        bookInterview={bookInterview}
        cancelInterview={cancelInterview}
      />
    );
  });

  return (
    <main className="layout">
      <section className="sidebar">
        <img
          className="sidebar--centered"
          src="images/logo.png"
          alt="Interview Scheduler"
        />
        <hr className="sidebar__separator sidebar--centered" />
        <nav className="sidebar__menu">
          <DayList
            days={state.days}
            value={state.day}
            onChange={setDay}
          />
        </nav>
        <img
          className="sidebar__lhl sidebar--centered"
          src="images/lhl.png"
          alt="Lighthouse Labs"
        />
      </section>
      <section className="schedule">
        {scheduleItems}
        <Appointment key="last" time="5pm" />
      </section>
    </main>
  );
}
